# Server Configuration
server:
  port: 3000

# Spring Datasource Configuration
spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/order_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  # Spring JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  # Spring Kafka Configuration
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: orderConfirmation:com

# Application-Specific Configuration
application:
  config:
    user-url: http://api-gateway:6000/api/v1/users
    payment-url: http://api-gateway:6000/api/v1/payments
    product-url: http://api-gateway:6000/api/v1/products
