# Server Configuration
server:
  port: 2000

# Spring Data MongoDB Configuration
spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: product_db
      authentication-database: admin
