# Server Configuration
server:
  port: 1000

# Spring Datasource Configuration
spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/user_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  # Spring JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
