server:
  port: 1000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
